src/Cygnus/Cygnus/Controllers/CoreRequestController.cs
using Cygnus.Managers;
using Cygnus.Nlp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cygnus.Controllers
{
    public class CoreRequestController : Controller
    {
        // GET: CoreRequest
        public ActionResult Index()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult Submit(string term)
        {
            IEnumerable<UserResponsePackage> responses = null;
            try
            {
                responses = NlpDecisionEngine.Instance.ExecuteQuery(term);
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }

            object response = "OK";
            if (responses != null && responses.FirstOrDefault() != null)
            { 
                response = responses.FirstOrDefault().Data;
            }

            return Json(response);
        }
    }
}

src/Cygnus/Cygnus/Views/CoreRequest/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@section Scripts
{
    <script src="@Url.Content("~/Scripts/jquery-ui.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui.min.js")"></script>
}

<h2>Index</h2>
@Html.Label("Enter your request")
<form action ="/" id="SearchForm" method="post">
    <input type="text" id="request" size="500"/>
    <button type="submit">Submit</button>
</form>
<div id="searchResponseArea">

</div>
<script type="text/javascript">
    $("#SearchForm").submit(function (event) {
        $.ajax({
            type: 'POST',
            url: "@(Url.Action("Submit", "CoreRequest"))",
            data: { "term": $("#request").val() },
            dataType: "json",
            success: function (data) {
                if (data) {
                    $("#searchResponseArea").html(data);
                }
            }
        });
        event.preventDefault();
    });
    
</script>